name: publish-cloudfront-action

author: Heronlabs

description: Publish Cloudfront

inputs:
  AWS_ROLE_TO_ASSUME:
    description: inputs.AWS_ROLE_TO_ASSUME
    required: true
  AWS_REGION:
    description: inputs.AWS_REGION
    required: true
  AWS_ROLE_DURATION_SECONDS:
    description: inputs.AWS_ROLE_DURATION_SECONDS
    required: true
  DISTRIBUTION_ID:
    description: inputs.DISTRIBUTION_ID
    required: true

runs:
  using: composite
  steps:
    - name: '[PUBLISH] | Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: ${{ inputs.AWS_ROLE_DURATION_SECONDS }}
        role-session-name: publish-cloudfront-action-session

    - name: '[PUBLISH] | Publish statics on AWS Cloudfront Bucket website'
      shell: bash
      run: |
        chmod +x ./publish-cloudfront-action/core/publish-cloudfront-bucket.sh
        ./publish-cloudfront-action/core/publish-cloudfront-bucket.sh
      env:
        DISTRIBUTION_ID: ${{ inputs.DISTRIBUTION_ID }}
